<header class="projectHeader left">
		<img class="left" src="public/images/shareable_energy.jpg" />
		<div class="left">
				<h1>Shareable enegry blocks</h1>
				<p>This project is in concept stage, the idea is to create shareable blocks of green energy. The blocks only should be charged by green energy generated by the owner.</p>
				<p><strong>Made by:</strong> <a href="user.php">Waag Society</a></p>
		</div>
</header>