<header class="projectHeader left">
		<img class="left" src="public/images/shareable_energy.jpg" />
		<div class="left">
				<h1>Shareable enegry blocks</h1>
				<p>This project is in concept stage, the idea is to create shareable blocks of green energy. The blocks only should be charged by green energy generated by the owner.</p>
				<p><strong>Made by:</strong> <a href="user.php">Waag Society</a></p>
				<p class="creativeCommons"><a href="https://creativecommons.org/licenses/by-nc/3.0/" target="_blank">Attribution 4.0 International <span class="icon-cc"></span> <span class="icon-cc-by"></span></a></p>
		</div>
</header>