<section class="userProjectVersions left">
	<h1 class="gamma">Designer's projects</h1>
	<ul class="projectVersionsList">
		<li>
			<article>
				<h1 class="epsilon">Shareable energy blocks</h1>
				<p>This project is in concept stage, the idea is to create shareable blocks of green energy. The blocks only should be charged by green energy generated by the owner. This also functions as an energy storage for when the owner is producing more energy than using.</p> 
				<a href="project.php" class="btn">View project</a>
			</article>
		</li>
	</ul>
</section>