<!DOCTYPE html>
<html lang="en-US" class="white">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="project description" />

    <title>Basic HTML start template</title>
    <link rel="icon" href="public/favicon.ico" type="image/x-icon">
    <link rel="stylesheet" type="text/css" href="public/stylesheets/main.css" />
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
</head>
<body class="projectPage">
    <?php include 'partials/navigation.html';?>
    <section class="mainSearch">
        <form class="left">
            <input placeholder="Search: description, tag, type of product">
            <button type="submit">Search</button>
        </form>
        <ul>
            <li>Type of machine</li>
            <li>Type of product</li>
            <li>Expanded search</li>
        </ul>
    </section>
    <section class="mainContent left">
        <header class="projectHeader left">
            <img class="left" src="public/images/shareable_energy.jpg" />
            <div class="left">
                <h1>Shareable enegry blocks</h1>
                <p>This project is in concept stage, the idea is to create shareable blocks of green energy. The blocks only should be charged by green energy generated by the owner. This also functions as an energy storage for when the owner is producing more energy than using.</p>
            </div>
        </header>
        <section class="projectDetails left">
            aaa
        </section>
        <section class="projectComments left">
            aaa
        </section>
    </section>
    <nav class="footerNav left">
        <section class="left">
            <ul>
                <li><h1>About us</h1></li>
                <li>Who are we?</li>
                <li>Our mission</li>
                <li>Help us out</li>
                <li>Media</li>
            </ul>
        </section>
        <section class="left">
            <ul>
                <li><h1>Inspired by</h1></li>
                <li>WikiPedia</li>
                <li>OpenDesk</li>
                <li>Fablab community</li>
                <li>WikiHouse</li>
            </ul>
        </section>
        <section class="left">
            <ul>
                <li><h1>General information</h1></li>
                <li>FAQ</li>
                <li>Contact us</li>
                <li>Give us feedback</li>
            </ul>
        </section>
        <section class="left">
            <ul>
                <li><h1>Partners</h1></li>
                <li>KABK</li>
                <li>Waag society</li>
                <li>Fablab</li>
            </ul>
        </section>
    </nav>
    <footer class="mainFooter">
        <p class="left">Webdesign made by <a href="#">Martinr.nl</a> feel free to download the designs <a href="#">here</a></p>
    </footer>
</body>
</html>

