<?php include 'partials/head.php';?>
<section class="mainContent left">
<header class="projectHeader left">
		<img class="left" src="public/images/shareable_energy.jpg" />
		<div class="left">
				<h1>Shareable enegry blocks</h1>
				<p>This project is in concept stage, the idea is to create shareable blocks of green energy. The blocks only should be charged by green energy generated by the owner. This also functions as an energy storage for when the owner is producing more energy than using.</p>
				<p><strong>Made by:</strong> <a href="user.php">Martin Risseeuw</a></p>
		</div>
</header>
<section class="projectDetails left">
	<ul>
		<li class="left">
			<a href="#">
				<span class="icon-icon_text"></span>
				<h5>Download</h5>
				<h6>manual & files</h6>
			</a>
		</li>
		<li class="left">
			<a href="user.php">
				<span class="icon-icon_hammer"></span>
				<h5>Ask</h5>
				<h6>the maker</h6>
			</a>
		</li>
		<li class="left">
			<span class="icon-icons_difficulty4"></span>
			<h5>Project</h5>
			<h6>difficulty</h6>
		</li>
		<li class="left">
			<span class="icon-icon_share"></span>
			<h5>Share</h5>
			<h6>project</h6>
		</li>
	</ul>
</section>
<section class="projectComments right">
	<header class="left">
		<div class="rating left">
			<p>Rate project: <span class="icon-icon_star"></span> <span class="icon-icon_star"></span> <span class="icon-icon_star"></span> <span class="icon-icon_star"></span> <span class="icon-icon_star"></span></p>
		</div>						
		<div class="right">
			<p class="viewcomments"><span class="icon-icon_down"></span>View comments</p>
		</div>
	</header>
	<ul class="left">
		<li>
			<article class="comment">
				<h1 class="gamma">What about the electronics</h1>
				<h2 class="zeta">Posted by: Martin Risseeuw</h2>
				<p>Selling excess solar or wind energy back to the power company is not a new idea. But what if, instead of selling renewable energy back to companies who then sell it to our neighbors, we could sell the energy directly to our neighbors?</p>
			</article>
		</li>
		<li>
			<article class="comment">
				<h1 class="gamma">What about the electronics</h1>
				<h2 class="zeta">Posted by: Martin Risseeuw</h2>
				<p>Selling excess solar or wind energy back to the power company is not a new idea. But what if, instead of selling renewable energy back to companies who then sell it to our neighbors, we could sell the energy directly to our neighbors?</p>
			</article>
		</li>
		<li>
			<article class="comment">
				<h1 class="gamma">What about the electronics</h1>
				<h2 class="zeta">Posted by: Martin Risseeuw</h2>
				<p>Selling excess solar or wind energy back to the power company is not a new idea. But what if, instead of selling renewable energy back to companies who then sell it to our neighbors, we could sell the energy directly to our neighbors?</p>
			</article>
		</li>
		<li>
			<article class="comment">
				<h1 class="gamma">What about the electronics</h1>
				<h2 class="zeta">Posted by: Martin Risseeuw</h2>
				<p>Selling excess solar or wind energy back to the power company is not a new idea. But what if, instead of selling renewable energy back to companies who then sell it to our neighbors, we could sell the energy directly to our neighbors?</p>
			</article>
		</li>
		<li>
			<article class="comment">
				<h1 class="gamma">What about the electronics</h1>
				<h2 class="zeta">Posted by: Martin Risseeuw</h2>
				<p>Selling excess solar or wind energy back to the power company is not a new idea. But what if, instead of selling renewable energy back to companies who then sell it to our neighbors, we could sell the energy directly to our neighbors?</p>
			</article>
		</li>
	</ul>
	<section class="commentInput left">
		<form class="left" >
			<h1 class="gamma">Add your comment</h1>
			<input placeholder="Name">
			<textarea placeholder="Your comment" rows="6"></textarea>
			<button class="left" ><span class="icon-icon_chat"></span> Submit comment</button>
		</form>
	</section>
</section>
<section class="projectVersions left">
	<h1 class="gamma left">Project versions</h1> 
	<ul class="projectVersionsList left">
		<li>
			<article>
				<h1 class="epsilon">10 file(s) updated by martinrisseeuw</h1>
				<p>I first started with creating the abstract version of the bourgie lamp with Rhinoceros (mac). I first drew the basic shape in Illustrator(image.1) after that I imported in Rhinoceros. I used the revolve command to create half of the lamps shape.</p> 
				<button><span class="icon-icon_save"></span> Download this version</button>
			</article>
		</li>
		<li>
			<article>
				<h1 class="epsilon">10 file(s) updated by martinrisseeuw</h1>
				<p>I first started with creating the abstract version of the bourgie lamp with Rhinoceros (mac). I first drew the basic shape in Illustrator(image.1) after that I imported in Rhinoceros. I used the revolve command to create half of the lamps shape.</p> 

				<p>After creating the model, I created two boxes and aligned them so I would have the pocket for the mold. One big box and one smaller box, so the model would have thickness at the sides. I created different holes for the connection width 8mm depth 5mm.</p>
				<button><span class="icon-icon_save"></span> Download this version</button>
			</article>
		</li>
		<li>
			<article>
				<h1 class="epsilon">10 file(s) updated by martinrisseeuw</h1>
				<p>I first started with creating the abstract version of the bourgie lamp with Rhinoceros (mac). I first drew the basic shape in Illustrator(image.1) after that I imported in Rhinoceros. I used the revolve command to create half of the lamps shape.</p> 

				<p>After creating the model, I created two boxes and aligned them so I would have the pocket for the mold. One big box and one smaller box, so the model would have thickness at the sides. I created different holes for the connection width 8mm depth 5mm.</p>
				<button><span class="icon-icon_save"></span> Download this version</button>
			</article>
		</li>
	</ul>
</section>
<section class="projectUpdate left">
	<form class="left" >
		<h1 class="beta">Upload your project version</h1>
		<p>Did you make any changes to this project? Share it with others and design & develop together.</p>
		<input type="file" name="fileToUpload" id="fileToUpload" multiple>
		<textarea placeholder="Version description" rows="6"></textarea>
		<button class="left" ><span class="icon-icon_save"></span> Submit</button>
	</form>
</section>
<script>
	$(document).on("click",".viewcomments", function () {
		$(".projectComments ul").slideToggle();
	});
</script>
</section>
<?php include 'partials/footer.php';?>