<!DOCTYPE html>
<html lang="en-US" class="white">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="project description" />

    <title>Basic HTML start template</title>
    <link rel="icon" href="public/favicon.ico" type="image/x-icon">
    <link rel="stylesheet" type="text/css" href="public/stylesheets/main.css" />
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
</head>
<body class="userPage">
    <?php include 'partials/navigation.html';?>
    <?php include 'partials/search.html';?>
    <section class="mainContent left">
        <header class="projectHeader left">
            <img class="left" src="public/images/martin_privacy_16-9.jpg" />
            <div class="left">
                <h1>Martin Risseeuw</h1>
							<p>Martin Risseeuw is an ambitious designer based in Amsterdam. After finishing his studies in interaction design, he started a bachelor programme of Interactive/Media/Design at the Royal Academy of Art in The Hague. He works as interaction designer for Waag Society. During his studies Martin developed a big interest in Social Design and interaction design. Martin’s view on the world is how to improve interactions, products and even society.</p>
            </div>
        </header>
				<section class="projectDetails left">
					<ul>
						<li class="left">
							<a href="#">
								<span class="icon-icon_text"></span>
								<h5>Download</h5>
								<h6>manual & files</h6>
							</a>
						</li>
						<li class="left">
							<a href="user.php">
								<span class="icon-icon_hammer"></span>
								<h5>Contact</h5>
								<h6>maker</h6>
							</a>
						</li>
						<li class="left">
							<span class="icon-icon_vinyl"></span>
							<h5>Project</h5>
							<h6>difficulty</h6>
						</li>
						<li class="left">
							<span class="icon-icon_share"></span>
							<h5>Share</h5>
							<h6>project</h6>
						</li>
					</ul>
        </section>
        <section class="projectComments right">
					<section class="commentInput left">
						<form class="left" >
							<h1 class="gamma">Ask the designer a question</h1>
							<input placeholder="name">
							<textarea placeholder="comment body" rows="6"></textarea>
							<button class="left" >Submit comment</button>
						</form>
					</section>
        </section>
				<section class="projectVersions left">
					<h1 class="gamma">Designer's projects</h1>
					<ul class="projectVersionsList">
						<li>
							<article>
								<h1 class="epsilon">Shareable energy blocks</h1>
								<p>This project is in concept stage, the idea is to create shareable blocks of green energy. The blocks only should be charged by green energy generated by the owner. This also functions as an energy storage for when the owner is producing more energy than using.</p> 
								<a href="project.php" class="btn">View project</a>
							</article>
						</li>
					</ul>
				</section>
			
    </section>
    <?php include 'partials/footernav.html';?>
    <footer class="mainFooter">
        <p class="left">Webdesign made by <a href="#">Martinr.nl</a> feel free to download the designs <a href="#">here</a></p>
    </footer>
	
		<script>
			$(".viewcomments").click(function(){
				$(".projectComments ul").slideToggle();
			});
		</script>
	
</body>
</html>

